[package]
name = "ghwcli"
version = "0.1.0"
authors = ["Sam Saint-Pettersen <s.stpettersen+github@gmail.com>"]

[dependencies]
curl = "0.4.3"
clioptions = "0.1.0"
text-diff = "0.4.0"
rustc-serialize = "0.3.22"
regex = "0.2.1"
select = "0.2.2"
